# Generated by Django 4.1.7 on 2023-04-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("summIApp", "0005_alter_useruploadedfiles_is_file_uploaded_on_imgbb"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSummaryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(default="", help_text="Summary for the image"),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        help_text="Image used for the summary",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="summIApp.useruploadedfiles",
                    ),
                ),
            ],
        ),
    ]
