# Generated by Django 4.1.7 on 2023-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summIApp", "0006_usersummaryhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "USE_OCR_APIs",
                    models.BooleanField(default=True, help_text="Use google OCR APIs?"),
                ),
                (
                    "SAVE_UPLOADED_IMAGES_LOCALLY",
                    models.BooleanField(
                        default=False,
                        help_text="Save User uploaded images to local disk?",
                    ),
                ),
            ],
        ),
    ]
